[package]
name = "redefined"
version = "0.1.0"
edition = "2021"

[lib]
name = "redefined"

[dependencies]
# derive
redefined-derive = { path = "../redefined-derive" }


[dev-dependencies]
redefined-outside-crate-tests = { path = "./outside-crate" }

# remote crate-io
primitive-types = "0.12"
ruint = "1.11.1"

# remote github
clickhouse = { git = "https://github.com/SorellaLabs/clickhouse.rs" }


[features]
default = ["unsafe", "remote"]
unsafe = ["redefined-derive/unsafe"]
remote = ["redefined-derive/remote"]